### ISSUE TITLE
Lua Script Error

### ISSUE THREAD

**Issue by crnvl** [kiwi515/gen4-RPC#1]
If you're trying to run the Lua Script with DeSmuME, this error is printed out in the Console.

`Initializing out.dat
D:\Emulator\Gen4RPC-master\RPC.lua:91: bad argument #1 to 'readdword' (number expected, got nil)
script stopped.
script finished running
`

OS: Win10
DeSmuME v0.9.11 x64

**Comment by lumierecia** [comment]
hi, how did you fix this?
